"""
Focus mode logic for Paixueji assistant.

This module contains functions for managing the focus mode state machine,
including depth/width transitions and object selection.

Functions:
    - decide_next_focus_mode: Determine next focus mode based on state
    - handle_width_wrong_answer: Handle wrong answer in WIDTH mode
    - generate_object_suggestions: Generate AI suggestions for new objects
"""
import json
import random
from loguru import logger


def decide_next_focus_mode(assistant) -> dict:
    """
    Determine next focus mode based on system-managed focus state.

    Returns:
        dict: {
            'focus_mode': str,  # 'depth', 'width_color', 'width_shape', 'width_category', or 'object_selection'
            'reason': str,  # Explanation for the decision
            'suggested_objects': list[str] | None,  # Objects to present if mode = 'object_selection'
            'reset_object': bool  # Whether to reset object state
        }
    """
    if not assistant.system_managed_focus:
        # Not in system-managed mode, return current manual focus
        return {
            'focus_mode': assistant.current_focus_mode,
            'reason': 'Manual focus mode',
            'suggested_objects': None,
            'reset_object': False
        }

    # RULE 1: DEPTH phase (4-5 questions)
    if assistant.current_focus_mode == 'depth':
        if assistant.depth_questions_count < assistant.depth_target:
            # Continue with DEPTH
            return {
                'focus_mode': 'depth',
                'reason': f'Depth phase: {assistant.depth_questions_count}/{assistant.depth_target} questions asked',
                'suggested_objects': None,
                'reset_object': False
            }
        else:
            # Switch to WIDTH mode (choose which category)
            available = [c for c in ['color', 'shape', 'category'] if c not in assistant.width_categories_tried]
            if not available:
                # All WIDTH categories tried? Shouldn't happen but fallback
                available = ['color', 'shape', 'category']
                assistant.width_categories_tried = []

            width_category = random.choice(available)
            assistant.current_focus_mode = f'width_{width_category}'
            assistant.width_categories_tried.append(width_category)

            return {
                'focus_mode': assistant.current_focus_mode,
                'reason': f'Completed depth phase ({assistant.depth_questions_count} questions). Switching to WIDTH: {width_category}',
                'suggested_objects': None,
                'reset_object': False
            }

    # RULE 2: WIDTH phase - handle wrong answers
    elif assistant.current_focus_mode.startswith('width_'):
        # Note: Wrong answer detection happens in validation
        # This function is called AFTER wrong answer is detected

        # Check if 3 consecutive wrong WIDTH answers
        if assistant.width_wrong_count >= 3:
            # Present object selection
            logger.info(f"[SYSTEM_MANAGED] 3 consecutive wrong WIDTH answers. Triggering object selection.")

            # Generate suggested objects (this will be done via AI)
            return {
                'focus_mode': 'object_selection',
                'reason': '3 consecutive wrong WIDTH answers detected',
                'suggested_objects': None,  # Will be generated by AI
                'reset_object': False
            }

        # Not at threshold yet, continue with current WIDTH or try next category
        # (Decision to switch WIDTH category happens elsewhere)
        return {
            'focus_mode': assistant.current_focus_mode,
            'reason': f'WIDTH mode: {assistant.width_wrong_count}/3 wrong answers',
            'suggested_objects': None,
            'reset_object': False
        }

    # RULE 3: OBJECT_SELECTION mode - waiting for user to pick
    elif assistant.current_focus_mode == 'object_selection':
        return {
            'focus_mode': 'object_selection',
            'reason': 'Awaiting object selection from user',
            'suggested_objects': None,
            'reset_object': False
        }

    # Fallback
    return {
        'focus_mode': 'depth',
        'reason': 'Fallback to depth mode',
        'suggested_objects': None,
        'reset_object': False
    }


def handle_width_wrong_answer(assistant) -> dict:
    """
    Handle wrong answer in WIDTH mode - decide whether to switch WIDTH category.

    Returns:
        dict: {
            'switch_category': bool,
            'new_focus_mode': str | None,
            'reason': str
        }
    """
    assistant.width_wrong_count += 1
    logger.info(f"[SYSTEM_MANAGED] Wrong WIDTH answer. Count: {assistant.width_wrong_count}/3")

    # Check if threshold reached
    if assistant.width_wrong_count >= 3:
        return {
            'switch_category': False,
            'new_focus_mode': None,
            'reason': '3 wrong answers reached - will trigger object selection'
        }

    # Try next WIDTH category if available
    available = [c for c in ['color', 'shape', 'category'] if c not in assistant.width_categories_tried]

    if not available:
        # All categories tried, stay on current
        return {
            'switch_category': False,
            'new_focus_mode': None,
            'reason': 'All WIDTH categories already tried this object'
        }

    # Switch to next category
    next_category = random.choice(available)
    new_mode = f'width_{next_category}'
    assistant.current_focus_mode = new_mode
    assistant.width_categories_tried.append(next_category)

    return {
        'switch_category': True,
        'new_focus_mode': new_mode,
        'reason': f'Switching WIDTH category to {new_mode}'
    }


async def generate_object_suggestions(assistant, config, client, age: int) -> list[str]:
    """
    Use AI to generate 3-4 related object suggestions.

    Args:
        assistant: PaixuejiAssistant instance
        config: Config dict
        client: Gemini client
        age: Child's age

    Returns:
        List of 3-4 object names
    """
    prompt = f"""The child (age {age}) has been learning about {assistant.object_name}.

Suggest 3-4 NEW objects that would be interesting for them to explore next.

Guidelines:
- Objects should be age-appropriate ({age} years old)
- Objects should be concrete and familiar
- Vary difficulty and category
- Make them engaging and fun

Respond with ONLY a JSON array of object names:
["object1", "object2", "object3", "object4"]
"""

    try:
        # Using async client
        response = await client.aio.models.generate_content(
            model=config.get("model_name", "gemini-2.5-flash-lite"),
            contents=prompt,
            config={
                "response_mime_type": "application/json",
                "temperature": 0.7,  # Higher temp for variety
                "max_output_tokens": 100
            }
        )

        objects = json.loads(response.text)
        logger.info(f"[OBJECT_SUGGESTIONS] Generated: {objects}")
        return objects[:4]  # Ensure max 4

    except Exception as e:
        logger.error(f"[OBJECT_SUGGESTIONS] Error: {e}")
        # Fallback suggestions
        return ["apple", "dog", "car", "tree"]
